### ISSUE TITLE
Possible concurrent type check of the same model during startup

### ISSUE THREAD

**Issue by lausdahl** [overturetool/overture#322]
It looks like it is possible to trigger two type checks concurrently!
Discovered in 2.1.1-SNAPSHOT
~~~
Type Checking: AlarmSL
Type Checking: AlarmSL
java.util.ConcurrentModificationException
	at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:953)
	at java.util.LinkedList$ListItr.next(LinkedList.java:886)
	at org.overture.ast.node.NodeList$NodeListIterator.next(NodeList.java:240)
	at org.overture.ast.node.NodeList$NodeListIterator.next(NodeList.java:225)
	at org.overture.typechecker.utilities.type.PTypeResolver.caseAFunctionType(PTypeResolver.java:176)
	at org.overture.typechecker.utilities.type.PTypeResolver.caseAFunctionType(PTypeResolver.java:53)
	at org.overture.ast.types.AFunctionType.apply(AFunctionType.java:333)
	at org.overture.typechecker.assistant.type.PTypeAssistantTC.typeResolve(PTypeAssistantTC.java:137)
	at org.overture.typechecker.utilities.DefinitionTypeResolver.caseAExplicitFunctionDefinition(DefinitionTypeResolver.java:93)
	at org.overture.typechecker.utilities.DefinitionTypeResolver.caseAExplicitFunctionDefinition(DefinitionTypeResolver.java:46)
	at org.overture.ast.definitions.AExplicitFunctionDefinition.apply(AExplicitFunctionDefinition.java:519)
	at org.overture.typechecker.assistant.definition.PDefinitionAssistantTC.typeResolve(PDefinitionAssistantTC.java:285)
	at org.overture.typechecker.ModuleTypeChecker.typeCheck(ModuleTypeChecker.java:204)
	at org.overture.ide.builders.vdmj.BuilderSl.typeCheck(BuilderSl.java:76)
	at org.overture.ide.builders.vdmj.VdmjBuilder.buildModel(VdmjBuilder.java:25)
	at org.overture.ide.builders.vdmj.BuilderSl.buildModel(BuilderSl.java:55)
	at org.overture.ide.core.builder.AbstractVdmBuilder.buildModel(AbstractVdmBuilder.java:39)
	at org.overture.ide.core.builder.SafeBuilder$1.run(SafeBuilder.java:102)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.overture.ide.core.builder.SafeBuilder.run(SafeBuilder.java:134)
java.util.ConcurrentModificationException
~~~

**Comment by joey-coleman** [comment]
Can this be reproduced?

**Comment by peterwvj** [comment]
I haven't noticed this behaviour for a long time so I'm closing this for now.
