### ISSUE TITLE
Confirmed memory leak

### ISSUE THREAD

**Issue by ldcouto** [overturetool/overture#364]
When doing longer modelling sessions, we've noticed that Overture gets slower over time. This is the classic symptom of a memory leak somewhere.

PVJ managed to trigger an error that pretty much confirms this (see below). Unfortunately the error does not really point to a root cause so we will have to a lengthier audit of UI code.

This issue may be best left in the backburner until we start looking at the trial migration to Eclipse 4. That will be a good time to look at UI stuff.

```java
java.lang.OutOfMemoryError: PermGen space
       at java.lang.ClassLoader.defineClass1(Native Method)
       at java.lang.ClassLoader.defineClass(Unknown Source)
       at org.eclipse.osgi.internal.loader.ModuleClassLoader.defineClass(ModuleClassLoader.java:272)
       at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.defineClass(ClasspathManager.java:632)
       at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:588)
       at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:540)
       at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:527)
       at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:324)
       at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:311)
       at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:386)
       at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:336)
       at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:328)
       at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
       at java.lang.ClassLoader.loadClass(Unknown Source)
       at org.eclipse.ui.internal.progress.ProgressManager$2.done(ProgressManager.java:466)
       at org.eclipse.core.internal.jobs.JobListeners$3.notify(JobListeners.java:42)
       at org.eclipse.core.internal.jobs.JobListeners.doNotify(JobListeners.java:102)
       at org.eclipse.core.internal.jobs.JobListeners.done(JobListeners.java:155)
       at org.eclipse.core.internal.jobs.JobManager.endJob(JobManager.java:655)
       at org.eclipse.core.internal.jobs.WorkerPool.endJob(WorkerPool.java:105)
       at org.eclipse.core.internal.jobs.Worker.run(Worker.java:71)
```

**Comment by peterwvj** [comment]
This could be a problem with Kepler https://bugs.eclipse.org/bugs/show_bug.cgi?id=436964

After next release we should move to Luna

**Comment by peterwvj** [comment]
After we moved to Luna I haven't experienced this problem. So maybe this is a problem with Kepler. Anyways, I'll close this issue for now.
