### ISSUE TITLE
Code generation giving bug for the AutomatedStockBrokerPP standard example

### ISSUE THREAD

**Issue by pglvdm** [overturetool/overture#400]
It gives the following bug:
~~~
java.lang.NullPointerException
	at org.overture.codegen.cgast.NodeList.setParent(NodeList.java:51)
	at org.overture.codegen.cgast.NodeList.add(NodeList.java:74)
	at org.overture.codegen.cgast.NodeList.add(NodeList.java:46)
	at org.overture.codegen.assistant.TypeAssistantCG.consMethodType(TypeAssistantCG.java:303)
	at org.overture.codegen.visitor.TypeVisitorCG.caseAFunctionType(TypeVisitorCG.java:291)
	at org.overture.codegen.visitor.TypeVisitorCG.caseAFunctionType(TypeVisitorCG.java:80)
	at org.overture.ast.types.AFunctionType.apply(AFunctionType.java:333)
	at org.overture.codegen.visitor.CGVisitor.defaultINode(CGVisitor.java:43)
	at org.overture.codegen.visitor.CGVisitorRecursiveTypeHandler.defaultINode(CGVisitorRecursiveTypeHandler.java:35)
	at org.overture.codegen.visitor.CGVisitorRecursiveTypeHandler.defaultINode(CGVisitorRecursiveTypeHandler.java:12)
	at org.overture.ast.analysis.QuestionAnswerAdaptor.defaultPType(QuestionAnswerAdaptor.java:1804)
	at org.overture.ast.analysis.QuestionAnswerAdaptor.caseAFunctionType(QuestionAnswerAdaptor.java:1844)
	at org.overture.ast.types.AFunctionType.apply(AFunctionType.java:333)
	at org.overture.codegen.visitor.DeclVisitorCG.caseAExplicitFunctionDefinition(DeclVisitorCG.java:180)
	at org.overture.codegen.visitor.DeclVisitorCG.caseAExplicitFunctionDefinition(DeclVisitorCG.java:71)
	at org.overture.ast.definitions.AExplicitFunctionDefinition.apply(AExplicitFunctionDefinition.java:531)
	at org.overture.codegen.visitor.CGVisitor.defaultINode(CGVisitor.java:43)
	at org.overture.codegen.visitor.CGVisitor.defaultINode(CGVisitor.java:30)
	at org.overture.ast.analysis.QuestionAnswerAdaptor.defaultPDefinition(QuestionAnswerAdaptor.java:2574)
	at org.overture.ast.analysis.QuestionAnswerAdaptor.defaultSFunctionDefinition(QuestionAnswerAdaptor.java:2634)
	at org.overture.ast.analysis.QuestionAnswerAdaptor.caseAExplicitFunctionDefinition(QuestionAnswerAdaptor.java:2794)
	at org.overture.ast.definitions.AExplicitFunctionDefinition.apply(AExplicitFunctionDefinition.java:531)
	at org.overture.codegen.visitor.DeclVisitorCG.caseAExplicitOperationDefinition(DeclVisitorCG.java:336)
	at org.overture.codegen.visitor.DeclVisitorCG.caseAExplicitOperationDefinition(DeclVisitorCG.java:71)
	at org.overture.ast.definitions.AExplicitOperationDefinition.apply(AExplicitOperationDefinition.java:386)
	at org.overture.codegen.visitor.CGVisitor.defaultINode(CGVisitor.java:43)
	at org.overture.codegen.visitor.CGVisitor.defaultINode(CGVisitor.java:30)
	at org.overture.ast.analysis.QuestionAnswerAdaptor.defaultPDefinition(QuestionAnswerAdaptor.java:2574)
	at org.overture.ast.analysis.QuestionAnswerAdaptor.defaultSOperationDefinition(QuestionAnswerAdaptor.java:2654)
	at org.overture.ast.analysis.QuestionAnswerAdaptor.caseAExplicitOperationDefinition(QuestionAnswerAdaptor.java:2814)
	at org.overture.ast.definitions.AExplicitOperationDefinition.apply(AExplicitOperationDefinition.java:386)
	at org.overture.codegen.visitor.ClassVisitorCG.caseAClassClassDefinition(ClassVisitorCG.java:92)
	at org.overture.codegen.visitor.ClassVisitorCG.caseAClassClassDefinition(ClassVisitorCG.java:54)
	at org.overture.ast.definitions.AClassClassDefinition.apply(AClassClassDefinition.java:323)
	at org.overture.codegen.visitor.CGVisitor.defaultINode(CGVisitor.java:43)
	at org.overture.codegen.visitor.CGVisitor.defaultINode(CGVisitor.java:30)
	at org.overture.ast.analysis.QuestionAnswerAdaptor.defaultPDefinition(QuestionAnswerAdaptor.java:2574)
	at org.overture.ast.analysis.QuestionAnswerAdaptor.defaultSClassDefinition(QuestionAnswerAdaptor.java:2604)
	at org.overture.ast.analysis.QuestionAnswerAdaptor.caseAClassClassDefinition(QuestionAnswerAdaptor.java:2974)
	at org.overture.ast.definitions.AClassClassDefinition.apply(AClassClassDefinition.java:323)
	at org.overture.codegen.ir.IRGenerator.generateFrom(IRGenerator.java:51)
	at org.overture.codegen.vdm2java.JavaCodeGen.generateJavaFromVdm(JavaCodeGen.java:256)
	at org.overture.ide.plugins.codegen.commands.Vdm2JavaCommand$1.run(Vdm2JavaCommand.java:191)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
~~~

**Comment by peterwvj** [comment]
A new issue has been created for this bug: #402
