### ISSUE TITLE
UI null pointer on Mac when type checking pure ops in SL

### ISSUE THREAD

**Issue by pglvdm** [overturetool/overture#498]
On a Mac I get an error report as:
~~~
java.lang.NullPointerException
	at org.eclipse.swt.widgets.Control.internal_new_GC(Control.java:2118)
	at org.eclipse.swt.graphics.GC.cocoa_new(GC.java:207)
	at org.eclipse.swt.widgets.Tree.sendMeasureItem(Tree.java:2613)
	at org.eclipse.swt.widgets.Tree.cellSize(Tree.java:288)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5528)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper_stret(Native Method)
	at org.eclipse.swt.widgets.Widget.expansionFrameWithFrame_inView(Widget.java:798)
	at org.eclipse.swt.widgets.Tree.expansionFrameWithFrame_inView(Tree.java:1283)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5907)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend_bool(Native Method)
	at org.eclipse.swt.internal.cocoa.NSRunLoop.runMode(NSRunLoop.java:42)
	at org.eclipse.swt.widgets.Display.sleep(Display.java:4691)
	at org.eclipse.ui.application.WorkbenchAdvisor.eventLoopIdle(WorkbenchAdvisor.java:368)
	at org.eclipse.ui.internal.ide.application.IDEWorkbenchAdvisor.eventLoopIdle(IDEWorkbenchAdvisor.java:918)
	at org.eclipse.ui.internal.Workbench$3.eventLoopIdle(Workbench.java:498)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
~~~
with a small adjustment of the cashdispenser standard exercise. It looks like:
~~~
state System of
  accounts : map AccountId to Account
  illegalCards : set of CardId
  curCard : map TillId to [Card]
  cardOk : map TillId to bool
  retainedCards : map TillId to set of Card
inv mk_System(accs,-,curCard,cardOk,-) == 
      dom curCard subset dom cardOk and
      (forall tid in set dom curCard &
         curCard(tid) = nil => not cardOk(tid)) and 
      (forall id1, id2 in set dom accs &
        id1 <> id2 =>
        dom accs(id1).cards inter dom accs(id2).cards = {})
init s == s = mk_System({|->},{},{mk_token("t1") |-> nil},
                        {mk_token("t1") |-> false},{|->})
end

types
  Account :: cards : map CardId to Cardholder
             balance : nat
             transactions : seq of Transaction
  inv account == TransactionsInvariant(account.transactions);

  Transaction :: date : Date
                 cardId : CardId
                 amount : nat;

  Card :: code : Code
          cardId : CardId
          accountId : AccountId;

  Cardholder :: name : Name;

  AccountId = nat;
  Name = seq of char;
  CardId = nat;
  Code = nat;
  PinCode = nat;
  Date = seq of char;
  TillId = token;

functions

  TransactionsInvariant : seq of Transaction +> bool
  TransactionsInvariant(ts) ==
    forall date in set {ts(i).date | i in set inds ts} &
      DateTotal(date,ts) <= dailyLimit;

  DateTotal : Date * seq of Transaction +> nat
  DateTotal(date,ts) ==
    Sum([ts(i).amount | i in set inds ts & ts(i).date = date]);

values
  dailyLimit : nat = 2000;

operations

  InsertCard : TillId * Card ==> ()
  InsertCard(tid,c) ==
    curCard(tid) := c
  pre tid in set dom curCard and curCard(tid) = nil;

  Validate : TillId * PinCode ==> <PinOk> | <PinNotOk> | <Retained>        
  Validate(tid,pin) ==
    let codeOk = curCard(tid).code = Encode(pin),
        cardLegal = IsLegalCard(curCard(tid)) 
    in
      (if not cardLegal then 
        (retainedCards(tid) := retainedCards(tid) union {curCard(tid)};
         cardOk(tid) := false;
         curCard(tid) := nil;
         return <Retained>)
       else
         cardOk(tid) := codeOk;
       return if cardOk(tid)
              then <PinOk>
              else <PinNotOk>)
  pre tid in set dom curCard and
      curCard(tid) <> nil and not cardOk(tid);

  ReturnCard : TillId ==> ()
  ReturnCard(tid) ==
    (cardOk(tid)  := false;
     curCard(tid) := nil)
  pre tid in set dom curCard and curCard(tid) <> nil;

  GetBalance : TillId ==> nat
  GetBalance(tid) ==
    return accounts(curCard(tid).accountId).balance
  pre tid in set dom curCard and
      curCard(tid) <> nil and cardOk(tid) and IsLegalCard(curCard(tid));

  MakeWithdrawal : TillId * nat * Date ==> bool
  MakeWithdrawal(tid,amount,date) ==
    let mk_Card(-,cardId,accountId) = curCard(tid),
        transaction = mk_Transaction(date,cardId,amount)        
    in
      if accounts(accountId).balance - amount >= 0 and 
        DateTotal(date,accounts(accountId).transactions^[transaction])
        <= dailyLimit
      then
        (accounts(accountId).balance := 
           accounts(accountId).balance - amount;
         accounts(accountId).transactions := 
           accounts(accountId).transactions ^ [transaction];
         return true)
     else 
       return false
  pre tid in set dom curCard and
      curCard(tid) <> nil and cardOk and IsLegalCard(curCard(tid));

  RequestStatement : TillId ==> Name * seq of Transaction * nat
  RequestStatement(tid) ==
    let mk_Card(-,cardId,accountId) = curCard(tid),
        mk_Account(cards,balance,transactions) = accounts(accountId)
    in
      return mk_(cards(cardId).name,transactions,balance)
  pre tid in set dom curCard and
      curCard(tid) <> nil and cardOk and IsLegalCard(curCard(tid));

  pure IsLegalCard : Card ==> bool
  IsLegalCard(mk_Card(-,cardId,accountId)) ==
    return cardId not in set illegalCards and 
           accountId in set dom accounts and
           cardId in set dom accounts(accountId).cards;

  ReportIllegalCard : CardId ==> ()
  ReportIllegalCard(cardId) ==
    illegalCards := illegalCards union {cardId};

  AddAccount : AccountId * Account ==> ()
  AddAccount(accountId,account) ==
    accounts := accounts munion {accountId |-> account}
  pre accountId not in set dom accounts;

functions
  Encode: PinCode +> Code
  Encode(pin) ==
    pin; -- NB The actual encoding procedure has not yet been chosen

  Sum: seq of real +> real
  Sum(rs) ==
    if rs = [] then 0
    else
      hd rs + Sum(tl rs)
  measure Len;

  Len: seq of real +> nat
  Len(list) ==
    len list;
~~~

**Comment by peterwvj** [comment]
@ldcouto I just tried this model in 2.3.0 and there is no problem on Linux. According to the stacktrace this looks like a MAC UI related issue.

**Comment by peterwvj** [comment]
I asked Kenneth to look at it since he is using a MAC

**Comment by ldcouto** [comment]
There's a good chance it's not specifically related to pure ops but for now...

**Comment by lausdahl** [comment]
Unable to replicate the reported error which seems to be about the SWT GC.

However, there is for sure something wrong with the spec / checking of it:

Error reported on last line of the following code:
> Multiple markers found on this line:
>  - Left hand of and is not bool.  
>  - Impure operation 'IsLegalCard' cannot be called from here.  


```
  RequestStatement : TillId ==> Name * seq of Transaction * nat
  RequestStatement(tid) ==
    let mk_Card(-,cardId,accountId) = curCard(tid),
        mk_Account(cards,balance,transactions) = accounts(accountId)
    in
      return mk_(cards(cardId).name,transactions,balance)
  pre tid in set dom curCard and
      curCard(tid) <> nil and cardOk and IsLegalCard(curCard(tid));
```

using

```
  pure IsLegalCard : Card ==> bool
  IsLegalCard(mk_Card(-,cardId,accountId)) ==
    return cardId not in set illegalCards and 
           accountId in set dom accounts and
           cardId in set dom accounts(accountId).cards;
```

- `cardOk` only exists as part of the state but as a map so it cannot be used like this.
- `IsLegalCard` is declared as pure so there should not be an error about *impure* here. If it is impure then it should be on the operations that declares it `pure` but turns out not to respect this.

I'm closing the issue since we cannot not do anything about the SWT framework. It will be upgraded to a newer version once we upgrade the Eclipse version, but as usual this brings new issues with it too.
