### ISSUE TITLE
Type checker: Null pointer error when type checking the 'is' expression

### ISSUE THREAD

**Issue by peterwvj** [overturetool/overture#504]
If you type check the model below it produces a NPE in the type checker.

The stacktrace is:
~~~
ava.lang.NullPointerException
	at org.overture.typechecker.visitor.QualificationVisitor.caseAIsExp(QualificationVisitor.java:67)
	at org.overture.typechecker.visitor.QualificationVisitor.caseAIsExp(QualificationVisitor.java:43)
	at org.overture.ast.expressions.AIsExp.apply(AIsExp.java:387)
	at org.overture.typechecker.visitor.TypeCheckerExpVisitor.caseAAndBooleanBinaryExp(TypeCheckerExpVisitor.java:260)
	at org.overture.typechecker.visitor.TypeCheckerExpVisitor.caseAAndBooleanBinaryExp(TypeCheckerExpVisitor.java:92)
	at org.overture.ast.expressions.AAndBooleanBinaryExp.apply(AAndBooleanBinaryExp.java:243)
	at org.overture.typechecker.visitor.TypeCheckVisitor.defaultPExp(TypeCheckVisitor.java:101)
	at org.overture.typechecker.visitor.TypeCheckVisitor.defaultPExp(TypeCheckVisitor.java:43)
	at org.overture.ast.analysis.QuestionAnswerAdaptor.defaultSBinaryExp(QuestionAnswerAdaptor.java:654)
	at org.overture.ast.analysis.QuestionAnswerAdaptor.defaultSBooleanBinaryExp(QuestionAnswerAdaptor.java:1344)
	at org.overture.ast.analysis.QuestionAnswerAdaptor.caseAAndBooleanBinaryExp(QuestionAnswerAdaptor.java:1544)
	at org.overture.ast.expressions.AAndBooleanBinaryExp.apply(AAndBooleanBinaryExp.java:243)
	at org.overture.typechecker.visitor.TypeCheckerExpVisitor.binaryCheck(TypeCheckerExpVisitor.java:3639)
	at org.overture.typechecker.visitor.TypeCheckerExpVisitor.defaultSBooleanBinaryExp(TypeCheckerExpVisitor.java:251)
	at org.overture.typechecker.visitor.TypeCheckerExpVisitor.caseAAndBooleanBinaryExp(TypeCheckerExpVisitor.java:267)
	at org.overture.typechecker.visitor.TypeCheckerExpVisitor.caseAAndBooleanBinaryExp(TypeCheckerExpVisitor.java:92)
	at org.overture.ast.expressions.AAndBooleanBinaryExp.apply(AAndBooleanBinaryExp.java:243)
	at org.overture.typechecker.visitor.TypeCheckVisitor.defaultPExp(TypeCheckVisitor.java:101)
	at org.overture.typechecker.visitor.TypeCheckVisitor.defaultPExp(TypeCheckVisitor.java:43)
	at org.overture.ast.analysis.QuestionAnswerAdaptor.defaultSBinaryExp(QuestionAnswerAdaptor.java:654)
	at org.overture.ast.analysis.QuestionAnswerAdaptor.defaultSBooleanBinaryExp(QuestionAnswerAdaptor.java:1344)
	at org.overture.ast.analysis.QuestionAnswerAdaptor.caseAAndBooleanBinaryExp(QuestionAnswerAdaptor.java:1544)
	at org.overture.ast.expressions.AAndBooleanBinaryExp.apply(AAndBooleanBinaryExp.java:243)
	at org.overture.typechecker.visitor.TypeCheckerDefinitionVisitor.caseAExplicitFunctionDefinition(TypeCheckerDefinitionVisitor.java:358)
	at org.overture.typechecker.visitor.TypeCheckerDefinitionVisitor.caseAExplicitFunctionDefinition(TypeCheckerDefinitionVisitor.java:107)
	at org.overture.ast.definitions.AExplicitFunctionDefinition.apply(AExplicitFunctionDefinition.java:531)
	at org.overture.typechecker.visitor.TypeCheckVisitor.defaultPDefinition(TypeCheckVisitor.java:108)
	at org.overture.typechecker.visitor.TypeCheckVisitor.defaultPDefinition(TypeCheckVisitor.java:43)
	at org.overture.ast.analysis.QuestionAnswerAdaptor.defaultSFunctionDefinition(QuestionAnswerAdaptor.java:2634)
	at org.overture.ast.analysis.QuestionAnswerAdaptor.caseAExplicitFunctionDefinition(QuestionAnswerAdaptor.java:2794)
	at org.overture.ast.definitions.AExplicitFunctionDefinition.apply(AExplicitFunctionDefinition.java:531)
	at org.overture.typechecker.ModuleTypeChecker.typeCheck(ModuleTypeChecker.java:235)
	at org.overture.ide.builders.vdmj.BuilderSl.typeCheck(BuilderSl.java:97)
	at org.overture.ide.builders.vdmj.VdmjBuilder.buildModel(VdmjBuilder.java:46)
	at org.overture.ide.builders.vdmj.BuilderSl.buildModel(BuilderSl.java:76)
	at org.overture.ide.core.builder.AbstractVdmBuilder.buildModel(AbstractVdmBuilder.java:42)
	at org.overture.ide.core.builder.SafeBuilder$1.run(SafeBuilder.java:105)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.overture.ide.core.builder.SafeBuilder.run(SafeBuilder.java:137)
~~~

~~~
module Test
exports all
definitions 

types 
Sort = <Agent> | <Number> | <SeqNumber> | <PublicKey> | <SymmetricKey> | <Function> | <Purpose> | <Untyped> | <Certified> | <Protocol>;

Type = BaseType | CatType; -- | FunType; perhaps

BaseType :: 
sort: Sort
parametric: bool
-- only these can be parametric
-- TODO: not true? <Function>, and <Keys> can also be parametric by agent
--inv mk_BaseType(s, p) == p => s in set { <Number>, <Agent>, <SeqNumber> };
inv mk_BaseType(s, p) == p => s in set { <Agent>, <Number>, <SeqNumber>, <PublicKey>, <SymmetricKey>, <Function> }; 

-- KPS results could be partial when kps_Id is still parametric
KPSResult = <Success> | <Partial> | <Failure>;

CatType ::
typs: seq1 of Type;

functions 

has_sort: [Type] * Sort -> bool
has_sort(x, s) == x <> nil and is_BasicType(x) and t(x).sort = s;

end Test
~~~

**Comment by nickbattle** [comment]
It's OK in VDMJ, so it's probably a visitor thing:
```
Parsed 1 module in 0.14 secs. No syntax errors
Error 3113: Unknown type name 'BasicType' in 'Test' (test.vdm) at line 27:32
Error 3182: Name 't' is not in scope in 'Test' (test.vdm) at line 27:52
Type checked 1 module in 0.01 secs. Found 2 type errors
Bye
```

**Comment by nickbattle** [comment]
Looks like a missing null check. I've pushed a fix to ncb/development.

**Comment by peterwvj** [comment]
Great and thanks Nick.
