### ISSUE TITLE
Type checker crashes when trying to call invalid CPU constructor

### ISSUE THREAD

**Issue by peterwvj** [overturetool/overture#584]
Consider the spec below.. Note that the spec tries to instantiate a CPU object without passing the priority and speed information required.

~~~
system S

instance variables

public static cpu1 : CPU := new CPU();

end S
~~~

If you try to type check it using Overture 2.3.8 then the tool crashes:

```bash
peter@peter-pc:~/dev/vdm/ovr-cmd$ java -jar commandlinetool-2.3.8-jar-with-dependencies.jar -vdmrt /home/peter/dev/vdm/Overture/ws/A/S.vdmrt
Parsed 1 class in 0.055 secs. No syntax errors
java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
Type checked 3 classes in 0.021 secs. Found 1 type error
```

There are indications that this is type checker related. The problem does not occur in VDMJ.

```Java

java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
	at java.util.LinkedList.get(LinkedList.java:476)
	at org.overture.typechecker.utilities.ImplicitDefinitionFinder.defaultSClassDefinition(ImplicitDefinitionFinder.java:120)
	at org.overture.typechecker.utilities.ImplicitDefinitionFinder.defaultSClassDefinition(ImplicitDefinitionFinder.java:69)
	at org.overture.ast.analysis.QuestionAdaptor.caseASystemClassDefinition(QuestionAdaptor.java:2964)
	at org.overture.ast.definitions.ASystemClassDefinition.apply(ASystemClassDefinition.java:311)
	at org.overture.typechecker.assistant.definition.PDefinitionAssistantTC.implicitDefinitions(PDefinitionAssistantTC.java:290)
	at org.overture.typechecker.assistant.definition.SClassDefinitionAssistantTC.implicitDefinitions(SClassDefinitionAssistantTC.java:259)
	at org.overture.typechecker.ClassTypeChecker.typeCheck(ClassTypeChecker.java:122)
	at org.overture.ide.builders.vdmj.BuilderPp.typeCheck(BuilderPp.java:91)
	at org.overture.ide.builders.vdmj.BuilderRt.typeCheck(BuilderRt.java:67)
	at org.overture.ide.builders.vdmj.VdmjBuilder.buildModel(VdmjBuilder.java:46)
	at org.overture.ide.builders.vdmj.BuilderPp.buildModel(BuilderPp.java:72)
	at org.overture.ide.core.builder.AbstractVdmBuilder.buildModel(AbstractVdmBuilder.java:42)
	at org.overture.ide.core.builder.SafeBuilder$1.run(SafeBuilder.java:105)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.overture.ide.core.builder.SafeBuilder.run(SafeBuilder.java:137)
```

**Comment by nickbattle** [comment]
It looks like Overture has some extra checks that VDMJ doesn't perform, relating to the speed of the CPU. Those checks are made in the implicit definition finder, but it is making an assumption about the number of arguments being passed to the CPU constructor.

If you change line 120 of ImplicitDefinitionFinder to:
```
PExp exp = newExp.getArgs().size() > 0 ? newExp.getArgs().get(1) : null;
```
Then it gets further and reports:
```
Error 3305: CPU frequency to slow: 0.0 Hz in 'S' (test.vpp) at line 5:15
Error 3297: Cannot use default constructor for this class in 'S' (test.vpp) at line 5:29
```
I'd rather not fix this on the ncb branches at the moment (else this will be mixed with RMs 35/36).

**Comment by peterwvj** [comment]
Thanks, Nick. I'll make sure it gets added.

**Comment by peterwvj** [comment]
The fix is available on `pvj/main`
