### ISSUE TITLE
Overture crashes when using top bar for file switching

### ISSUE THREAD

**Issue by nina-j** [overturetool/overture#652]
### Description

The Overture tool crashes when I use the top bar for file switching
![screenshot from 2017-10-31 09-24-54](https://user-images.githubusercontent.com/28903001/32213884-62d930a6-be1d-11e7-8054-6db2b6765608.png)

with the following error message:

![image](https://user-images.githubusercontent.com/28903001/32214023-d639c056-be1d-11e7-9893-2d86904cb679.png)

All other Overture functionality works as expected.

### Steps to Reproduce

1. Click a file on the top bar
2. Overture crashes

**Expected behavior:** File switching

**Actual behavior:** Overture crashes

**Reproduces how often:** 100% of the time

### Versions

**Overture:** v. 2.5.2
**OS:** Antergos Linux x86_64
Host: SVP1321C5E C60C6NCW
Kernel: 4.13.8-1-ARCH
**Java:** The following Java versions are available for me, default is the one currently selected.
Available Java environments:
  java-7-openjdk
  java-8-jre/jre (default)
  java-8-openjdk
  java-9-jdk

### Additional Information

Here is a log paste of the issue. Note that it displays Arch since AntergOS is just a prepackaged Arch distro.

```eclipse.buildId=unknown
java.version=1.8.0_144
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_DK
Command-line arguments:  -os linux -ws gtk -arch x86_64

org.eclipse.ui
Error
Tue Oct 31 09:20:43 CET 2017
Unhandled event loop exception

org.eclipse.swt.SWTError: No more handles
	at org.eclipse.swt.SWT.error(SWT.java:4559)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.graphics.Cursor.<init>(Cursor.java:173)
	at org.eclipse.swt.widgets.Display.getSystemCursor(Display.java:2688)
	at org.eclipse.e4.ui.workbench.addons.dndaddon.DragAgent.dragFinished(DragAgent.java:157)
	at org.eclipse.e4.ui.workbench.addons.dndaddon.PartDragAgent.dragFinished(PartDragAgent.java:93)
	at org.eclipse.e4.ui.workbench.addons.dndaddon.DnDManager.finishDrag(DnDManager.java:285)
	at org.eclipse.e4.ui.workbench.addons.dndaddon.DnDManager.startDrag(DnDManager.java:252)
	at org.eclipse.e4.ui.workbench.addons.dndaddon.DnDManager$1.dragDetected(DnDManager.java:89)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:128)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5227)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4561)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4151)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

**Comment by nickbattle** [comment]
Hi monochromagic. When you say, "the top bar", do you mean switching between tabs in the editor view? This is a very basic function and seems to be working for me. Can you never switch between editors or not between VDM++ and VDM-SL or perhaps only with some file loaded in the editor? Can you narrow down the circumstances when it occurs in any way?

**Comment by monochromagic** [comment]
Yes, exactly, using the tabs for switching makes Overture crash. File type doesn't matter. 
I can close the file tabs just fine, but not press them to open them - this makes the editor crash. I have been editing both VDM-SL and VDM++ files, and it occurs with any mix of these. Text files also have the issue. 

Actually, I don't think it's the switching that causes the issue. It seems to simply be the act of clicking a file name in the tab bar.

**Comment by nickbattle** [comment]
That's strange. It certainly doesn't happen for me - that's 64-bit openSUSE with Java 8. The error stack trace seems to have a drag event in progress? What might that be?

**Comment by nina-j** [comment]
It appears when opening Overture after a crash:

![image](https://user-images.githubusercontent.com/28903001/32319450-e4583ed0-bfba-11e7-8c97-497dc7b0013b.png)

Overture also crashes when I click the tab named drag placeholder. In fact, it crashes anywhere I click where tabs are involved.

**Comment by nickbattle** [comment]
I've never seen a View called "Drag Placeholder" before. Have you loaded other Eclipse plugins into Overture?

There are some open bugs in Eclipse to do with drag and drop of views in a perspective. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=492861. Are you trying to re-order the workspace perspective at all?

**Comment by peterwvj** [comment]
I can't produce this problem on Linux (Ubuntu 17.04). I think this could be a problem with Eclipse (like Nick suggests). Can you produce this problem using fresh Overture installation that does not have additional plugins installed?

**Comment by nina-j** [comment]
The installation is fresh - I have no plugins. Eclipse is not even installed on my system, could that be an issue?

**Comment by peterwvj** [comment]
No that shouldn't be a problem, Overture should work as long as you have Java installed.

I'm curious to know whether this problem also happens if you're using a plain version of Eclipse. Currently, Overture builds against Eclipse Neon, which you can down here http://www.eclipse.org/downloads/packages/release/Neon/3 . Can you produce this issue using that version of Eclipse?

Another thing: what version of GTK are you using? On my Linux distro the command `dpkg -l libgtk*` provides me with information about the relevant packages.

**Comment by nickbattle** [comment]
Also, could you provide us with a step by step description of what you do to cause the issue - right from starting up Overture? I know you said in the original post that you just click on the tab bar, but obviously you must (what?) open a project and then open more than one source file first, and so on.

I still don't understand why the stack trace is showing us a drag-and-drop error; that would mean you were dragging one of the tabs? Can you try with a different mouse or a track pad? - there might be an issue with the mouse events that are being generated by your device.

**Comment by peterwvj** [comment]
@nina-j Did you get a chance to try any of the above suggestions? You could also try to use the newest test builds, which build against a newer version of Eclipse. You can download the test builds here:
http://overture.au.dk/overture/test/

**Comment by peterwvj** [comment]
@nina-j has confirmed that this was a problem with her machine.
