### ISSUE TITLE
Java Exception when running debug on AlarmSL sample project.

### ISSUE THREAD

**Issue by olafur-skulason** [overturetool/overture#687]
### Description

[Description of the issue]

### Steps to Reproduce

1. Follow tutorial 003 downloading AlarmSL
2. Get to section 3.5.1. Open Debug Configuration
3. Get exception.

**Expected behavior:** [What you expect to happen]
Run debugging
**Actual behavior:** [What actually happens]
Get Exception
java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:134)
	at org.overture.interpreter.debug.DBGPReader.write(DBGPReader.java:660)
	at org.overture.interpreter.debug.DBGPReaderV2.xcmdOvertureResponse(DBGPReaderV2.java:874)
	at org.overture.interpreter.debug.DBGPReaderV2.processWriteCoverage(DBGPReaderV2.java:2043)
	at org.overture.interpreter.debug.DBGPReaderV2.processOvertureCmd(DBGPReaderV2.java:1871)
	at org.overture.interpreter.debug.DBGPReaderV2.process(DBGPReaderV2.java:703)
	at org.overture.interpreter.debug.DBGPReader.run(DBGPReader.java:845)
	at org.overture.interpreter.debug.DBGPReader.connect(DBGPReader.java:554)
	at org.overture.interpreter.debug.DBGPReader.startup(DBGPReader.java:562)
	at org.overture.interpreter.debug.DBGPReaderV2.main(DBGPReaderV2.java:533)

**Reproduces how often:** [What percentage of the time does it reproduce?]
Happens each time. 
### Versions
Overture 2.6.2
Ubuntu 16.04
Which version of Overture are you using? Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

By accident did I start doing the SL tutorial. I will be moving to the correct PP tutorial, will not be following the issue.

**Comment by peterwvj** [comment]
Thanks for reporting. Could you please provide a reference to the tutorial you are referring to or (even better) outline  more accurately the steps to produce the errors.

**Comment by nickbattle** [comment]
I think he's saying he won't follow this issue, and without more information we cannot progress it. So closing.
